baseURL = "http://localhost"
title = "Pillerseetreffen"
theme = 'hugo-theme-relearn'

pluralizeListTitles = false


# Required if you want to render robots.txt template
enableRobotsTXT = true

languageCode = "de"
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages]

  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = "Pillerseetreffen"
    weight = 10

  [[languages.de.menu.shortcuts]]
  name = "<i class='fa-regular fa-eye'></i> Beobachter"
  identifier = "ds"
  url = "beobachter/"
  weight = 50

  [[languages.de.menu.shortcuts]]
  name = "<i class='fa-solid fa-map-location-dot'></i> Fundorte"
  url = "fundorte/"
  weight = 51

  [[languages.de.menu.shortcuts]]
  name = "<i class='fa-regular fa-handshake'></i> Treffen"
  identifier = "hugodoc"
  url = "treffen/"
  weight = 60

  [[languages.de.menu.shortcuts]]
  name = "<i class='fa-solid fa-layer-group'></i> Kategorien"
  url = "categories/"
  weight = 70

  [[languages.de.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Stichworte"
  url = "tags/"
  weight = 80

[[languages.de.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Impressum"
  url = "impressum/"
  weight = 90

[[languages.de.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Datenschutz"
  url = "datenschutz/"
  weight = 100

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Pillerseemeeting"
    weight = 20

  [[languages.en.menu.shortcuts]]
  name = "<i class='fa-regular fa-eye'></i> Observers"
  identifier = "ds"
  url = "beobachter/"
  weight = 10

  [[languages.en.menu.shortcuts]]
  name = "<i class='fa-solid fa-map-location-dot'></i> Places"
  url = "fundorte/"
  weight = 11

  [[languages.en.menu.shortcuts]]
  name = "<i class='fa-regular fa-handshake'></i> Meetings"
  identifier = "hugodoc"
  url = "treffen/"
  weight = 20

  [[languages.en.menu.shortcuts]]
  name = "<i class='fa-solid fa-layer-group'></i> Categories"
  url = "categories/"
  weight = 30

  [[languages.en.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Tags"
  url = "tags/"
  weight = 40

[[languages.en.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Impressum"
  url = "impressum/"
  weight = 90

[[languages.en.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Privacy Policy"
  url = "datenschutz/"
  weight = 100

[params]
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  collapsibleMenu = true
  titleSeparator = ": "
  additionalContentLanguage = [ "de", "en" ]
  disableMenuTitle=false
  disableShortcutsTitle = false

  [[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Relearn Light/Dark'

  [[params.themeVariant]]
    identifier = 'relearn-light'

  [[params.themeVariant]]
    identifier = 'relearn-dark'

  [[params.themeVariant]]
    identifier = 'relearn-bright'

  [[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    auto = ['learn', 'neon']
    identifier = 'retro-auto'
    name = 'Retro Learn/Neon'

  [[params.themeVariant]]
    identifier = 'neon'

  [[params.themeVariant]]
    identifier = 'learn'

[outputs]
  home = ["HTML", "RSS", "PRINT"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.highlight]
    style = "monokai"

[markup.goldmark.renderer]
  unsafe= true

[module]
  [module.hugoVersion]
    min = "0.25"


[taxonomies]
   tag = "tags"
   category = "categories"
   Beobachter = "Beobachter"
   Fundort = "Fundorte"
   Treffen = "Treffen"




